work_dir: ./work_dir/smarthome/xsub/agcn_bone
model_saved_name: ./runs/smarthome_cs_agcn_bone
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/smarthome/xsub/train_data_bone.npy
  label_path: ./data/smarthome/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/smarthome/xsub/val_data_bone.npy
  label_path: ./data/smarthome/xsub/val_label.pkl

# model
model: model.agcn.Model
model_args:
  num_class: 31
  num_point: 15
  num_person: 1
  graph: graph.smarthome.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40]

# training
device: [0,1,2,3]
batch_size: 16
test_batch_size: 32
num_epoch: 80
nesterov: True
